import React, { useEffect, useState } from 'react';

import { Loader, FormField, CardList } from '../components'

const HomePage = () => {

  const [isLoading, setIsLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);
  const [searchText, setSearchText] = useState('');
  const [searchResults, setSearchResults] = useState(null);
  const [searchTimeOut, setSearchTimeOut] = useState(null);

  useEffect(() => {
    const fetchPosts = async () => {
      setIsLoading(true);
      try {
        const response = await fetch('https://mypixai.onrender.com/api/v1/post', {
          method: 'GET',
          headers: { 'Content-Type': 'application/json' }
        })

        if (response.ok) {
          const results = await response.json();
          setAllPosts(results.data.reverse());
        }
      } catch (error) {
        alert(error)
      } finally {
        setIsLoading(false);
      }
    }
    fetchPosts()
  }, [])

  const handleSearchChange = (e) => {
    clearTimeout(searchTimeOut);
    setSearchText(e.target.value);


    setSearchTimeOut(
      setTimeout(() => {
        const searchResults = allPosts.filter((item) =>
          item.name.toLowerCase().includes(searchText.toLowerCase()) ||
          item.prompt.toLowerCase().includes(searchText.toLowerCase()));

        setSearchResults(searchResults)
      }, 500)
    )
  }

  return (
    <section className="mx-auto max-w-7xl">
      <div>
        <h1 className="font-extrabold text-[#222328] text-[32px]">
          Welcome to the Showcase
        </h1>
        <p className="mt-2 text-[#666e75] text-[16] max-w[500px]">
          This collection of imaginative and visually stunning pix generated by DALL-E A.I
        </p>
      </div>

      <div className="mt-8">
        <FormField labelName="Search Pix" type="text" name="text"
          value={searchText} handleChange={handleSearchChange}
          placeholder="Search photos by description or a name" />
      </div>

      <div className="mt-10 ">
        {isLoading
          ? (
            <div className="flex justify-center items-center">
              <Loader />
            </div>
          ) : (
            <>
              {searchText && (
                <h2 className='font-medium text-[#666e75] text-xl mb-3'>
                  Showing results for
                  <span className='text-[#222328]'> {searchText}</span>
                </h2>
              )}
              <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
                {searchText
                  ? (
                    <CardList data={searchResults} title={`Try something else.`} />
                  ) : (
                    <CardList data={allPosts} title='No posts found' />
                  )}

              </div>
            </>
          )}
      </div>
    </section>
  )
}

export default HomePage